services:
  app:
    build:
      context: .
    image: cfs-server
    container_name: cfs-server
    ports:
      - "8080:8080"
    depends_on:
      - cfs-postgres
      - cfs-minio
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cfs-postgres:5432/cfs-postgres-db
      - SPRING_DATASOURCE_USERNAME=cfs
      - SPRING_DATASOURCE_PASSWORD=cfs
      - MINIO_ENDPOINT=http://cfs-minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=user-files
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - mynetwork

  cfs-postgres:
    image: postgres:16.1
    container_name: cfs-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=cfs
      - POSTGRES_USER=cfs
      - POSTGRES_DB=cfs-postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  cfs-minio:
    image: minio/minio
    container_name: cfs-minio
    ports:
      - "9000:9000"  # API MinIO
      - "9001:9001"  # Панель управления MinIO
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - mynetwork

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mynetwork
    restart: always

volumes:
  postgres-data:
  minio-data:
  redis-data:

networks:
  mynetwork:
    driver: bridge